[/Script/GameplayTags.GameplayTagsList]

; Attribute Modifier trigger events
GameplayTagList=(Tag="SimpleGAS.ModiferActionTriggers.OnApplied", DevComment="Broadcast when a modifier is initially applied to an ability component")
GameplayTagList=(Tag="SimpleGAS.ModiferActionTriggers.OnTick", DevComment="Broadcast when a duration modifier ticks")
GameplayTagList=(Tag="SimpleGAS.ModiferActionTriggers.OnTickFailedSkip", DevComment="Broadcast when a duration modifier fails to tick and has TickTagRequirementBehaviour == CancelOnTagRequirementFailed")
GameplayTagList=(Tag="SimpleGAS.ModiferActionTriggers.OnTickFailedCancel", DevComment="Broadcast when a duration modifier fails to tick and has TickTagRequirementBehaviour == SkipOnTagRequirementFailed")
GameplayTagList=(Tag="SimpleGAS.ModiferActionTriggers.OnEnded", DevComment="Broadcast when a duration modifier ends successfully")
GameplayTagList=(Tag="SimpleGAS.ModiferActionTriggers.OnCancelled", DevComment="Broadcast when a duration modifier is cancelled prematurely")

; Attribute Modifier Action scratchpad tags
GameplayTagList=(Tag="SimpleGAS.ModifierActionScratchpadTags.FloatAttributeOverflow", DevComment="A scratchpad entry used to keep track of float attribute overflow")